### ISSUE TITLE
Expand to use Amazon Glacier

### ISSUE THREAD

**Issue by toastwaffle** [ms4720/s3sync#4]
Would it be possible to expand s3sync to work with the new Amazon Glacier service? I use s3 to store an archived copy of my laptop, and don't often interact with it, so Glacier would be a damn sight cheaper.

**Comment by mat813** [comment]
You could use a Lifecycle on your bucket to move things to Glacier a day or two after you upload them. No ?

**Comment by toastwaffle** [comment]
I never even knew that feature existed - it even works with a 0-day delay. Thanks!
